apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ppwiq46ai-python
  janus-idp.io/tekton: ppwiq46ai-python
  backstage.io/kubernetes-id: ppwiq46ai-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ppwiq46ai-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
