apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ppwiq46ai-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ppwiq46ai-python 
  name: ppwiq46ai-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ppwiq46ai-python 
